name: Last Commmunion
favicon: null
layout_spectrum: 0.3943085551727563
typography_spectrum: 0.21171626169234514
title: A Memoir of a Man Adopted by an Alien
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7908989866264164
  lightness: 0.0569538043346256
  saturation: 0.7911409453954548
  rhythmicContrast: 0.47498471243306994
purpose: []
