name: Last Commmunion
favicon: null
layout_spectrum: 0.27023
typography_spectrum: 0.21171626169234514
title: A Memoir of a Man Adopted by an Alien
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#820024'
    - '#cb4e10'
    - '#9b9ab3'
    - '#d2d3e8'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
